# TCL File Generated by Component Editor 20.1
# Thu Dec 14 16:49:13 EST 2023
# DO NOT MODIFY


# 
# ads_seven_segment "seven segment display driver" v1.0
# John Lutz 2023.12.14.16:49:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ads_seven_segment
# 
set_module_property DESCRIPTION ""
set_module_property NAME ads_seven_segment
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "John Lutz"
set_module_property DISPLAY_NAME "seven segment display driver"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL seven_segment_agent
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file seven_seg_driver_pkg.vhd VHDL PATH seven_seg_driver_pkg.vhd
add_fileset_file seven_seg_top.vhd VHDL PATH seven_seg_top.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter lamp_mode_common_anode BOOLEAN true
set_parameter_property lamp_mode_common_anode DEFAULT_VALUE true
set_parameter_property lamp_mode_common_anode DISPLAY_NAME lamp_mode_common_anode
set_parameter_property lamp_mode_common_anode TYPE BOOLEAN
set_parameter_property lamp_mode_common_anode UNITS None
set_parameter_property lamp_mode_common_anode HDL_PARAMETER true
add_parameter decimal_support BOOLEAN true
set_parameter_property decimal_support DEFAULT_VALUE true
set_parameter_property decimal_support DISPLAY_NAME decimal_support
set_parameter_property decimal_support TYPE BOOLEAN
set_parameter_property decimal_support UNITS None
set_parameter_property decimal_support HDL_PARAMETER true
add_parameter implementer INTEGER 100
set_parameter_property implementer DEFAULT_VALUE 100
set_parameter_property implementer DISPLAY_NAME implementer
set_parameter_property implementer TYPE INTEGER
set_parameter_property implementer ENABLED false
set_parameter_property implementer UNITS None
set_parameter_property implementer HDL_PARAMETER true
add_parameter revision INTEGER 0
set_parameter_property revision DEFAULT_VALUE 0
set_parameter_property revision DISPLAY_NAME revision
set_parameter_property revision TYPE INTEGER
set_parameter_property revision ENABLED false
set_parameter_property revision UNITS None
set_parameter_property revision HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point lamps
# 
add_interface lamps conduit end
set_interface_property lamps associatedClock clock
set_interface_property lamps associatedReset ""
set_interface_property lamps ENABLED true
set_interface_property lamps EXPORT_OF ""
set_interface_property lamps PORT_NAME_MAP ""
set_interface_property lamps CMSIS_SVD_VARIABLES ""
set_interface_property lamps SVD_ADDRESS_GROUP ""

add_interface_port lamps lamps export Output 42


# 
# connection point avalon_agent_1
# 
add_interface avalon_agent_1 avalon end
set_interface_property avalon_agent_1 addressUnits WORDS
set_interface_property avalon_agent_1 associatedClock clock
set_interface_property avalon_agent_1 associatedReset reset
set_interface_property avalon_agent_1 bitsPerSymbol 8
set_interface_property avalon_agent_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_agent_1 burstcountUnits WORDS
set_interface_property avalon_agent_1 explicitAddressSpan 0
set_interface_property avalon_agent_1 holdTime 0
set_interface_property avalon_agent_1 linewrapBursts false
set_interface_property avalon_agent_1 maximumPendingReadTransactions 0
set_interface_property avalon_agent_1 maximumPendingWriteTransactions 0
set_interface_property avalon_agent_1 readLatency 0
set_interface_property avalon_agent_1 readWaitTime 1
set_interface_property avalon_agent_1 setupTime 0
set_interface_property avalon_agent_1 timingUnits Cycles
set_interface_property avalon_agent_1 writeWaitTime 0
set_interface_property avalon_agent_1 ENABLED true
set_interface_property avalon_agent_1 EXPORT_OF ""
set_interface_property avalon_agent_1 PORT_NAME_MAP ""
set_interface_property avalon_agent_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_agent_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_agent_1 address address Input 2
add_interface_port avalon_agent_1 read read Input 1
add_interface_port avalon_agent_1 readdata readdata Output 32
add_interface_port avalon_agent_1 write write Input 1
add_interface_port avalon_agent_1 writedata writedata Input 32
set_interface_assignment avalon_agent_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_agent_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_agent_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_agent_1 embeddedsw.configuration.isPrintableDevice 0

